// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: chatting.proto

// protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative chatting/chatting.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_chatting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_chatting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_chatting_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_chatting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_chatting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_chatting_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Room struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=roomName,proto3" json:"roomName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Room) Reset() {
	*x = Room{}
	mi := &file_chatting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_chatting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_chatting_proto_rawDescGZIP(), []int{2}
}

func (x *Room) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *Room) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_chatting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatting_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type RemoveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=RoomId,proto3" json:"RoomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoomRequest) Reset() {
	*x = RemoveRoomRequest{}
	mi := &file_chatting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoomRequest) ProtoMessage() {}

func (x *RemoveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoomRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoomRequest) Descriptor() ([]byte, []int) {
	return file_chatting_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveRoomRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type RoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        int32                  `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomRequest) Reset() {
	*x = RoomRequest{}
	mi := &file_chatting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomRequest) ProtoMessage() {}

func (x *RoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomRequest.ProtoReflect.Descriptor instead.
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return file_chatting_proto_rawDescGZIP(), []int{5}
}

func (x *RoomRequest) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_chatting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_chatting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_chatting_proto_rawDescGZIP(), []int{6}
}

func (x *Message) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_chatting_proto protoreflect.FileDescriptor

const file_chatting_proto_rawDesc = "" +
	"\n" +
	"\x0echatting.proto\x12\bchatting\"\a\n" +
	"\x05Empty\"\x1e\n" +
	"\x04User\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x05R\x06userId\":\n" +
	"\x04Room\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x05R\x06roomId\x12\x1a\n" +
	"\broomName\x18\x02 \x01(\tR\broomName\"/\n" +
	"\x11CreateRoomRequest\x12\x1a\n" +
	"\broomName\x18\x01 \x01(\tR\broomName\"+\n" +
	"\x11RemoveRoomRequest\x12\x16\n" +
	"\x06RoomId\x18\x01 \x01(\x05R\x06RoomId\"%\n" +
	"\vRoomRequest\x12\x16\n" +
	"\x06roomId\x18\x01 \x01(\x05R\x06roomId\"\x1b\n" +
	"\aMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg2\xaa\x03\n" +
	"\bChatting\x12(\n" +
	"\x05Login\x12\x0f.chatting.Empty\x1a\x0e.chatting.User\x12*\n" +
	"\x06Logout\x12\x0f.chatting.Empty\x1a\x0f.chatting.Empty\x120\n" +
	"\vGetChatRoom\x12\x0f.chatting.Empty\x1a\x0e.chatting.Room0\x01\x129\n" +
	"\n" +
	"CreateRoom\x12\x1b.chatting.CreateRoomRequest\x1a\x0e.chatting.Room\x12:\n" +
	"\n" +
	"RemoveRoom\x12\x1b.chatting.RemoveRoomRequest\x1a\x0f.chatting.Empty\x127\n" +
	"\rEnterChatRoom\x12\x15.chatting.RoomRequest\x1a\x0f.chatting.Empty\x120\n" +
	"\fExitChatRoom\x12\x0f.chatting.Empty\x1a\x0f.chatting.Empty\x124\n" +
	"\bChatting\x12\x11.chatting.Message\x1a\x11.chatting.Message(\x010\x01B\x83\x01\n" +
	"\fcom.chattingB\rChattingProtoP\x01Z$github.com/bufbuild/buf-examples/gen\xa2\x02\x03CXX\xaa\x02\bChatting\xca\x02\bChatting\xe2\x02\x14Chatting\\GPBMetadata\xea\x02\bChattingb\x06proto3"

var (
	file_chatting_proto_rawDescOnce sync.Once
	file_chatting_proto_rawDescData []byte
)

func file_chatting_proto_rawDescGZIP() []byte {
	file_chatting_proto_rawDescOnce.Do(func() {
		file_chatting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatting_proto_rawDesc), len(file_chatting_proto_rawDesc)))
	})
	return file_chatting_proto_rawDescData
}

var file_chatting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_chatting_proto_goTypes = []any{
	(*Empty)(nil),             // 0: chatting.Empty
	(*User)(nil),              // 1: chatting.User
	(*Room)(nil),              // 2: chatting.Room
	(*CreateRoomRequest)(nil), // 3: chatting.CreateRoomRequest
	(*RemoveRoomRequest)(nil), // 4: chatting.RemoveRoomRequest
	(*RoomRequest)(nil),       // 5: chatting.RoomRequest
	(*Message)(nil),           // 6: chatting.Message
}
var file_chatting_proto_depIdxs = []int32{
	0, // 0: chatting.Chatting.Login:input_type -> chatting.Empty
	0, // 1: chatting.Chatting.Logout:input_type -> chatting.Empty
	0, // 2: chatting.Chatting.GetChatRoom:input_type -> chatting.Empty
	3, // 3: chatting.Chatting.CreateRoom:input_type -> chatting.CreateRoomRequest
	4, // 4: chatting.Chatting.RemoveRoom:input_type -> chatting.RemoveRoomRequest
	5, // 5: chatting.Chatting.EnterChatRoom:input_type -> chatting.RoomRequest
	0, // 6: chatting.Chatting.ExitChatRoom:input_type -> chatting.Empty
	6, // 7: chatting.Chatting.Chatting:input_type -> chatting.Message
	1, // 8: chatting.Chatting.Login:output_type -> chatting.User
	0, // 9: chatting.Chatting.Logout:output_type -> chatting.Empty
	2, // 10: chatting.Chatting.GetChatRoom:output_type -> chatting.Room
	2, // 11: chatting.Chatting.CreateRoom:output_type -> chatting.Room
	0, // 12: chatting.Chatting.RemoveRoom:output_type -> chatting.Empty
	0, // 13: chatting.Chatting.EnterChatRoom:output_type -> chatting.Empty
	0, // 14: chatting.Chatting.ExitChatRoom:output_type -> chatting.Empty
	6, // 15: chatting.Chatting.Chatting:output_type -> chatting.Message
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatting_proto_init() }
func file_chatting_proto_init() {
	if File_chatting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatting_proto_rawDesc), len(file_chatting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatting_proto_goTypes,
		DependencyIndexes: file_chatting_proto_depIdxs,
		MessageInfos:      file_chatting_proto_msgTypes,
	}.Build()
	File_chatting_proto = out.File
	file_chatting_proto_goTypes = nil
	file_chatting_proto_depIdxs = nil
}
